### ISSUE TITLE
[Qt6] [Android] Creating New Keys Crashes the App

### ISSUE THREAD

**Issue by LeonnardoVerol** [frankosterfeld/qtkeychain#233]
- **qtkeychain Version: Master Branch**
- build: qmake

---

- Desktop
    - [OK] 5.15.2 (Old qtkeychain version)
    - [OK] 6.3.2
- Android (Emulator)
    - [OK] 5.15.2 (Old qtkeychain version)
    - [CRASH] 6.3.2 [Android OS 10] [SDK 29] [x86_x64]
    - [CRASH] 6.3.2 [Android OS 11] [SDK 31] [x86_x64]
    - [CRASH] 6.4.3 [Android OS 11] [SDK 31] [x86_x64]

---

On error, QtCreator jumps to file `androidkeystore.cpp` at:

```
KeyPairGeneratorSpec::Builder KeyPairGeneratorSpec::Builder::setAlias(const QString &alias) const
{
    return handleExceptions(callObjectMethod("setAlias",
                                             "(Ljava/lang/String;)Landroid/security/KeyPairGeneratorSpec$Builder;",
                                             fromString(alias).object()));
}

KeyPairGeneratorSpec::Builder KeyPairGeneratorSpec::Builder::setSubject(const X500Principal &subject) const
{
    return handleExceptions(callObjectMethod("setSubject",
                                             "(Ljavax/security/auth/x500/X500Principal;)Landroid/security/KeyPairGeneratorSpec$Builder;",
                                             subject.object()));
}
```

From `keychain_android.cpp`:

```
const auto &alias = makeAlias(q->service(), q->key());
    if (!keyStore.containsAlias(alias)) {
        const Calendar start = Calendar::getInstance();
        const Calendar end = Calendar::getInstance();
        end.add(Calendar::YEAR, 99);

        const KeyPairGeneratorSpec spec =
            #if QT_VERSION < QT_VERSION_CHECK(6, 0, 0)
                KeyPairGeneratorSpec::Builder(Context(QtAndroid::androidActivity())).
            #elif QT_VERSION < QT_VERSION_CHECK(6, 4, 0)
                KeyPairGeneratorSpec::Builder(QNativeInterface::QAndroidApplication::context()).
            #else
                KeyPairGeneratorSpec::Builder((jobject)QNativeInterface::QAndroidApplication::context()).
            #endif
                setAlias(alias).
                setSubject(X500Principal(QStringLiteral("CN=QtKeychain, O=Android Authority"))).
                setSerialNumber(java::math::BigInteger::ONE).
                setStartDate(start.getTime()).
                setEndDate(end.getTime()).
                build();

        const KeyPairGenerator generator = KeyPairGenerator::getInstance(QStringLiteral("RSA"),
                                                                         QStringLiteral("AndroidKeyStore"));

        if (!generator) {
            q->emitFinishedWithError(Error::OtherError, tr("Could not create private key generator"));
            return;
        }

        generator.initialize(spec);

        if (!generator.generateKeyPair()) {
            q->emitFinishedWithError(Error::OtherError, tr("Could not generate new private key"));
            return;
        }
    }
```

Top Error Stack :

```
W System.err: java.lang.NoSuchMethodError: no non-static method "Lorg/qtproject/qt/android/bindings/QtActivity;.setAlias(Ljava/lang/String;)Landroid/security/KeyPairGeneratorSpec$Builder;"
W System.err: 	at org.qtproject.qt.android.QtNative.startQtApplication(Native Method)
W System.err: 	at org.qtproject.qt.android.QtNative$7.run(QtNative.java:416)
W System.err: 	at org.qtproject.qt.android.QtThread$1.run(QtThread.java:25)
W System.err: 	at java.lang.Thread.run(Thread.java:920)
F le.W: java_vm_ext.cc:579] JNI DETECTED ERROR IN APPLICATION: GetMethodID received NULL jclass
F le.W: java_vm_ext.cc:579]     in call to GetMethodID
F le.W: java_vm_ext.cc:579]     from void org.qtproject.qt.android.QtNative.startQtApplication()
F le.W: runtime.cc:669] Runtime aborting...
F le.W: runtime.cc:669] Dumping all threads without mutator lock held
F le.W: runtime.cc:669] All threads:
F le.W: runtime.cc:669] DALVIK THREADS (35):
F le.W: runtime.cc:669] "qtMainLoopThread" prio=5 tid=23 Runnable
F le.W: runtime.cc:669]   | group="" sCount=0 ucsCount=0 flags=0 obj=0x134000f0 self=0x70a829de6520
F le.W: runtime.cc:669]   | sysTid=9341 nice=0 cgrp=top-app sched=0/0 handle=0x70a64b321cf0
F le.W: runtime.cc:669]   | state=R schedstat=( 650960736 228309703 2723 ) utm=36 stm=28 core=1 HZ=100
F le.W: runtime.cc:669]   | stack=0x70a64b21f000-0x70a64b221000 stackSize=1035KB
F le.W: runtime.cc:669]   | held mutexes= "abort lock" "mutator lock"(shared held)
```

**Comment by LeonnardoVerol** [comment]
Bug also happened running the Test Example Project

**Comment by LeonnardoVerol** [comment]
Updating existing keys seems to work but not creating new ones
